apiVersion: apps/v1
kind: Deployment
metadata:
  name: inboxia-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inboxia-redis
  template:
    metadata:
      labels:
        app: inboxia-redis
    spec:
      containers:
        - name: redis
          image: redis:7-alpine
          ports:
            - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: inboxia-redis
spec:
  selector:
    app: inboxia-redis
  ports:
    - port: 6379
      targetPort: 6379
